### ISSUE TITLE
Yarn install failed

### ISSUE THREAD

**Issue by sguiheux** [vladotesanovic/ngSemantic#114]
Restriction  engine in package.json do not allow user to use yarn package manager (https://github.com/yarnpkg/yarn)

`
error ng-semantic@1.1.11: The engine "node" is incompatible with this module. Expected version ">= 5.4.1 < 6".
`
There is a reason to not allow node > 6 ?

**Comment by Madsn** [comment]
Should no longer be an issue https://github.com/vladotesanovic/ngSemantic/pull/135

**Comment by keawade** [comment]
I just got the same error.

```
error ng-semantic@1.1.11: The engine "node" is incompatible with this module. Expected version ">= 5.4.1 < 6".
```

**Comment by vladotesanovic** [comment]
this is fixed now
