### ISSUE TITLE
How to call semantic functions inside typescript?

### ISSUE THREAD

**Issue by prayagmk** [vladotesanovic/ngSemantic#116]
Need to know how can i call semantic functions inside typescript.

showModal(){
   newModal.show();
}

Is there any way of doing this?

**Comment by anil1712** [comment]
For Modal you can do this.

In your template
`
<sm-modal #editSupplierModal>
`
in your component

`import { SemanticModalComponent } from 'ng-semantic';`

`@ViewChild('editSupplierModal') editSupplierModal: SemanticModalComponent;`
..
`this.editSupplierModal.show();`

You can check @alex88 comments. from below url. I have taken the solution from the same.
https://github.com/vladotesanovic/ngSemantic/issues/115

**Comment by prayagmk** [comment]
Thanks @anil1712 :+1:
