### ISSUE TITLE
jQuery(...).modal is not a function

### ISSUE THREAD

**Issue by govi2010** [vladotesanovic/ngSemantic#121]
hello , 
I have just clone https://github.com/AngularClass/angular2-webpack-starter and started adding ngSemantic in that repo.

Everythig went well .. but when i used sm-modal
and called show method . 
I got following error. 

<img width="1915" alt="screen shot 2016-11-01 at 5 28 41 pm" src="https://cloud.githubusercontent.com/assets/8776031/19889038/b7357ce2-a058-11e6-8ffa-d08657c19071.png">

 inline template:20:28 caused by: jQuery(...).modal is not a function

When i run

**Comment by mwamufiya** [comment]
ngSemantic, leverages jQuery. did you install jQuery and include it in your index file as referenced in [here](https://github.com/vladotesanovic/ngSemantic)

add a link to the jquery.js in your index.html

**Comment by vladotesanovic** [comment]
Yes, you should reference to jQuery and semantic.min.js files in your angular-cli.json, as @mwamufiya mentined

**Comment by govi2010** [comment]
@vladotesanovic  I have fixed this. Thank you.
