### ISSUE TITLE
Node engine version limit

### ISSUE THREAD

**Issue by Christian-Seematter** [vladotesanovic/ngSemantic#122]
I've got a node package that uses "ng-semenatic": "^1.1.11", however yarn install fails because ng-semantic restricts node versions > 6 in package.json:

> "engines": {
>     "node": ">= 5.4.1 < 6"
>   },

![image](https://cloud.githubusercontent.com/assets/1957259/19922837/5c217d72-a0dc-11e6-8fea-4ba583bef3d2.png)

This error can be circumvented with yarn install --ignore-engines, however I belive current node version to be supported. As far as I am aware npm does not check for this, yarn however does.

**Comment by vladotesanovic** [comment]
Ok, this should be changed.

I saw now that angular team also increased version in their repository, i ll do the same.

https://github.com/angular/angular/blob/master/package.json#L10

**Comment by Madsn** [comment]
I guess this can be closed now?

**Comment by vladotesanovic** [comment]
:+1: correct

**Comment by Christian-Seematter** [comment]
I've seen that the pull request for this was merged into master and build successfully. When will this be available via npm?
