### ISSUE TITLE
2 way data binding for rating module

### ISSUE THREAD

**Issue by kacepe** [vladotesanovic/ngSemantic#124]
Hello,
There is no 2 way data binding for rating module, I think it will be very helpful if we can bind it. 

Regards

**Comment by prayagmk** [comment]
@kacepe : Did you find any ways to do it. Because it will be really great full atleast if we can do it for [initialRating] attribute.

**Comment by prayagmk** [comment]
@kacepe : Did a little tweak in ng-semantic rating module. Not sure the right way to do it, but it works.

    ngOnChanges(changes: SimpleChanges) {
        if(changes['initialRating'] != null){
            jQuery(this.rating.nativeElement)
                .rating({
                    initialRating: changes['initialRating'].currentValue || 0,
                    maxRating: this.maxRating || 5,
                    onRate: (value: number) => {
                        this.onRate.emit(value);
                    }
            });
        }
    }
