### ISSUE TITLE
can't make it work on MACOS

### ISSUE THREAD

**Issue by mmazloum** [vladotesanovic/ngSemantic#13]
Here is the npm debug log : 

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'demo:build' ]
2 info using npm@3.8.3
3 info using node@v5.10.1
4 verbose run-script [ 'predemo:build', 'demo:build', 'postdemo:build' ]
5 info lifecycle ng-semantic@1.0.21~predemo:build: ng-semantic@1.0.21
6 silly lifecycle ng-semantic@1.0.21~predemo:build: no script for predemo:build, continuing
7 info lifecycle ng-semantic@1.0.21~demo:build: ng-semantic@1.0.21
8 verbose lifecycle ng-semantic@1.0.21~demo:build: unsafe-perm in lifecycle true
9 verbose lifecycle ng-semantic@1.0.21~demo:build: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/marwanmazloum/Desktop/Developpement/Cordon/ngSemantic/node_modules/.bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
10 verbose lifecycle ng-semantic@1.0.21~demo:build: CWD: /Users/marwanmazloum/Desktop/Developpement/Cordon/ngSemantic
11 silly lifecycle ng-semantic@1.0.21~demo:build: Args: [ '-c',
11 silly lifecycle   'rm -rf demo/app && tslint -c ./tslint.json \'src/app/**/*.ts\' && tsc -p \'./src\' --rootDir \'./src\' --outDir \'./demo\' && cd src && find . -name \'*.html\' | cpio -pdm ../demo' ]
12 silly lifecycle ng-semantic@1.0.21~demo:build: Returned: code: 1  signal: null
13 info lifecycle ng-semantic@1.0.21~demo:build: Failed to exec demo:build script
14 verbose stack Error: ng-semantic@1.0.21 demo:build: `rm -rf demo/app && tslint -c ./tslint.json 'src/app/**/*.ts' && tsc -p './src' --rootDir './src' --outDir './demo' && cd src && find . -name '*.html' | cpio -pdm ../demo`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:239:16)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at EventEmitter.emit (events.js:185:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at ChildProcess.emit (events.js:185:7)
14 verbose stack     at maybeClose (internal/child_process.js:850:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid ng-semantic@1.0.21
16 verbose cwd /Users/marwanmazloum/Desktop/Developpement/Cordon/ngSemantic
17 error Darwin 15.0.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "demo:build"
19 error node v5.10.1
20 error npm  v3.8.3
21 error code ELIFECYCLE
22 error ng-semantic@1.0.21 demo:build: `rm -rf demo/app && tslint -c ./tslint.json 'src/app/**/*.ts' && tsc -p './src' --rootDir './src' --outDir './demo' && cd src && find . -name '*.html' | cpio -pdm ../demo`
22 error Exit status 1
23 error Failed at the ng-semantic@1.0.21 demo:build script 'rm -rf demo/app && tslint -c ./tslint.json 'src/app/**/*.ts' && tsc -p './src' --rootDir './src' --outDir './demo' && cd src && find . -name '*.html' | cpio -pdm ../demo'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the ng-semantic package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     rm -rf demo/app && tslint -c ./tslint.json 'src/app/**/*.ts' && tsc -p './src' --rootDir './src' --outDir './demo' && cd src && find . -name '*.html' | cpio -pdm ../demo
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs ng-semantic
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls ng-semantic
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by TerryMooreII** [comment]
I also had issues getting this to work on a Mac.  What isnt stated in the docs is that you have to do a `npm install -g tslint typescript` before you run the other build commands.  

However the `npm build:demo` command still failed. 
I finally got past it when I ran each shell command that the `npm build:demo` does by hand. 
`rm -rf demo/app`
`tslint -c ./tslint.json 'src/app/**/*.ts'` 
`tsc -p './src' --rootDir './src' --outDir './demo'` 
`cd src && find . -name '*.html' | cpio -pdm ../demo`

Then everything built and worked.  

I am not sure why combining each shell commands in the npm run script fails. 

I hope this helps.

**Comment by vladotesanovic** [comment]
I removed unnecessary coping files, this should work now as well.
