### ISSUE TITLE
Issue at install in Linux (Mint)

### ISSUE THREAD

**Issue by Maes95** [vladotesanovic/ngSemantic#14]
I try: npm install `ng-semantic --save`

with this trace:

```
└── semantic-ui-card@2.1.7  extraneous

npm WARN optional Skipping failed optional dependency /karma/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.11
```

**Comment by TerryMooreII** [comment]
Which part of this trace is the install issue you are referring to?  
The extraneous or the npm WARN or something else?

**Comment by saitonakamura** [comment]
I'm gettting the same WARN message on Windows, but AFAIK it's only a warning, because dependency is optional, and should not affect your application
By the way the same message appears in angular2-quickstart, so I wonder if it comes from angular2 npm package itself

**Comment by vladotesanovic** [comment]
Outdated.
