### ISSUE TITLE
API for ngSemantic

### ISSUE THREAD

**Issue by rkrayovskyy** [vladotesanovic/ngSemantic#15]
Hello,

is there a way to use ngSemantic components programatically, through API?

My use case: load data from remote API, generate and show modal with this data.

thank you,
Roman

**Comment by vladotesanovic** [comment]
Consider this Plunker, 

I recreated and solve your problem here:
http://plnkr.co/edit/QVHFPLi5leGqRJ8ZEV4P?p=preview
