### ISSUE TITLE
semantic css files not available

### ISSUE THREAD

**Issue by mkndn** [vladotesanovic/ngSemantic#167]
I used the following npm command to install semantic
`npm install ng-semantic --save`
But i couldn't find css/scss/less files downloaded inside node_modules/ng-semantic folder. 

As a result my dropdown is not themed at all.

**Comment by enavarro222** [comment]
Semantic CSS are not provided by ngSemantic. You need to install semantic it self. It is possible with bower:
```
bower install semantic
```

**Comment by mkndn** [comment]
Thank you. i have downloaded the stylesheets. Looks like still the styling is not applied properly. I am using the select component. Please refer the attached images
![semanticselect](https://cloud.githubusercontent.com/assets/20502054/24093582/95402756-0d7a-11e7-9342-3074d675dae8.PNG)
![semanticselectexp](https://cloud.githubusercontent.com/assets/20502054/24093583/954309e4-0d7a-11e7-90c1-436a8dc86a1a.PNG)

In systemjs.config.js, 
```
map: {
'ng-semantic': 'node_modules/ng-semantic',
}
packages: {
'ng-semantic': { 
        main: 'ng-semantic.js',
        defaultExtension: 'js'
      }
}

```
and the import i used
`import { NgSemanticModule } from "ng-semantic";`

My HTML,
`<sm-select
        placeholder="Select ACO" 
        class="fluid"
        (onChange)="selected($event)">
        <option *ngFor="let item of items" [value]="item.id"><span [innerHTML]="item.text"></span></option>
      </sm-select>`

**Comment by mkndn** [comment]
My Apologies. I missed this import 
`<script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.2/semantic.min.js"></script>`
This solved the issue.
