### ISSUE TITLE
issue with importing link

### ISSUE THREAD

**Issue by mahajnamahmod** [vladotesanovic/ngSemantic#17]
at the getting started page the css link should be 

`"<link` rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.1.8/semantic.min.css"></link>"
 
instead of
`"<link` rel="stylesheet" type="text/css" link="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.1.8/semantic.min.css"></link>"

**Comment by vladotesanovic** [comment]
Fixed
