### ISSUE TITLE
Google fonts

### ISSUE THREAD

**Issue by zigzag95** [vladotesanovic/ngSemantic#19]
I see your css is depending from Internet as referencing Google fonts.
Could you please fix this by adding needed stuff in local assets or providing sass or css sources.

**Comment by vladotesanovic** [comment]
This depends on how you import semantic.min.css in your application. 

Right now, i did this for Demo on https://ng-semantic.herokuapp.com

You can see in source that i am pulling everything from local source now.

**Comment by zigzag95** [comment]
Thanks.
Your components are awesome.
