### ISSUE TITLE
Plans to implement dropdown selector?

### ISSUE THREAD

**Issue by Sijan117** [vladotesanovic/ngSemantic#21]
Just wanted to check if you're working on this currently or can I go ahead and give it a go?

**Comment by vladotesanovic** [comment]
Yes i have,

I already did some testings here: http://plnkr.co/edit/Egm4FcGSHdYDuFvsBdW7?p=preview

But please, feel free to make it or to contribute on anything else.

**Comment by Sijan117** [comment]
Roger that. Thanks a lot for your work, I'll try to contribute as soon as I can.

**Comment by poiati** [comment]
I'm trying to use a dropdown with multiple selection and NgModel. As you can guess it isn't work with the current implementation. I was digging into Angular2 source code and I think the only way to achieve this is by implementing a new `ControlValueAcessor`. Do you have any thought about this? I can help you with this one.
