### ISSUE TITLE
Dropdown - key down doesnt work as expected

### ISSUE THREAD

**Issue by lpotapczuk** [vladotesanovic/ngSemantic#25]
There is a bug, that doesn't allow user to select option using keyboard. - when I press key down, dropdown selects option for a second, and then goes back to the first object in collection.

**Comment by vladotesanovic** [comment]
Yes, that is true.

sm-dropdown is and sm-select is still under development, i will try to fix this ASAP

**Comment by lpotapczuk** [comment]
It's interesting bug. I've wrote my own wrapper around this component, and run into the same issue. Also, you can try to double click on the drop down - there is also weird behaviour there.

**Comment by lpotapczuk** [comment]
Actually, I've found this bug:

  #https://github.com/angular/zone.js/issues/319


Seems like this is a zone.js issue.
