### ISSUE TITLE
Dropdown published with wrong js file

### ISSUE THREAD

**Issue by Eduardo-M-Cavalcanti** [vladotesanovic/ngSemantic#26]
Maybe I am wrong, but I have found that the dropdown.js file installed with "npm install ng-semantic --save" present in ng-semantic/dropdown and ng-semantic/bundles/ng-semantic.js is the transpiled version of  master/demo/app/components/dropdown.ts. Hence, the component will not work.

**Comment by vladotesanovic** [comment]
Yea, sm-dropdown is not ready yet, let me fix it.

**Comment by vladotesanovic** [comment]
@Eduardo-M-Cavalcanti I think this is fixed with new version?
