### ISSUE TITLE
Possible bug in dropdown.ts: options override

### ISSUE THREAD

**Issue by Eduardo-M-Cavalcanti** [vladotesanovic/ngSemantic#27]
As I could not run sm-dropdown having it installed via npm (#26), I tried to make it run "directly" using dropdown.ts. Then  I verified that on dropdown setup, the "options" were overrriden. I could fix it with the following modification:

```
export class SemanticDropdownComponent implements AfterViewInit {
    @Input() class: string;
    @Input() title: string;
    @Input() items: Array<{}>;
    @Input() options: any = {};
    @Output() onChange: EventEmitter<string|number> = new EventEmitter<string|number>();
    @ViewChild("dropdown") dropdown: ElementRef;

    ngAfterViewInit(): void {
        this.options.onChange = (value: string|number) => this.onChange.emit(value)
        jQuery(this.dropdown.nativeElement).dropdown(this.options);
    }
}
```
Regards.

**Comment by vladotesanovic** [comment]
sm-dropdown is under development, it is not available via npm ( ng-semantic ) yet. 

I will publish first version of this module in next few days.

**Comment by Eduardo-M-Cavalcanti** [comment]
Hi Vlado,
What you have done already was of great help, thank you :)

**Comment by gruentee** [comment]
Hello Vlado, first of all: thanks for your great work!

I'm really looking forward to use the dropdown element and would greatly appreciate if someone could fix it soon. I'd love to contribute something myself, but I'm still quite new to AngularJS… maybe some time soon.

Best regards,
Constantin

**Comment by vladotesanovic** [comment]
@Eduardo-M-Cavalcanti @gruentee sm-dropdown and sm-select are published.

Although, they are not finished, lot of improvements coming.
