### ISSUE TITLE
SMTooltipDirective - Not show on hover 

### ISSUE THREAD

**Issue by jpsantosbh** [vladotesanovic/ngSemantic#28]
Don't if I miss something but doing like the example:

<button class="ui button" smDirTooltip="text..." smDirPosition="right center">Hover me</button>

Did not work.

The directive is call, but is not working!

**Comment by vladotesanovic** [comment]
Ok, can you tell me more about your setup? 

Can you publish it on GitHub?

**Comment by jpsantosbh** [comment]
Sorry,
about that the problem was conflict with a previuos version of semantic.

Not it's working 100%
