### ISSUE TITLE
Not possible to build

### ISSUE THREAD

**Issue by lukasfrank** [vladotesanovic/ngSemantic#30]
ng-semantic/tab/tab.ts(15,12): error TS2300: Duplicate identifier 'tab'.
ng-semantic/tab/tab.ts(18,21): error TS2300: Duplicate identifier 'tab'.
ng-semantic/tab/tab.ts(21,14): error TS2339: Property 'nativeElement' does not exist on type 'number'.
ng-semantic/tab/tab.ts(24,16): error TS2339: Property 'nativeElement' does not exist on type 'number'.
ng-semantic/tab/tab.ts(47,68): error TS2339: Property 'nativeElement' does not exist on type 'number'.

**Comment by vladotesanovic** [comment]
Thanks for reporing :+1: 

It is fixed now.
