### ISSUE TITLE
Popup not closing

### ISSUE THREAD

**Issue by jyosh** [vladotesanovic/ngSemantic#31]
Thanks for the angular2 port of semantic ui!

I just came across a bug in popup, if clicked on the trigger button for more than once the popup is not closing after clicking outside.

Also I would like to know how can I close the popup after clicking on a button within the popup?

Regards,
jyosh

**Comment by vladotesanovic** [comment]
Thanks for reporting. 

I fixed this, https://ng-semantic.herokuapp.com/#/elements/popup

now, you can explicitly hide popup window with: _myPopup.hide()_
