### ISSUE TITLE
Sidebar not opening after first open

### ISSUE THREAD

**Issue by croivzeba** [vladotesanovic/ngSemantic#33]
It happens to both left and bottom sidebars. Steps to reproduce:

1. open [demo](https://ng-semantic.herokuapp.com/#/elements/sidebar)
2. click on launch left sidebar
3. click anywhere to close the sidebar
4. click on launch left sidebar and notice it does not open again

Browsers tried:

* Chrome
* Firefox

I sadly could not find out why it does not work and apart from this I really enjoy using ngSemantic!

Cheers,

Ivo

**Comment by vladotesanovic** [comment]
Hey, thanks for reporting. 

It was small but nasty bug :)

I fixed this, you should update ngSemantic to 1.0.32 version.
