### ISSUE TITLE
Webpack Integration

### ISSUE THREAD

**Issue by JimmyMagee** [vladotesanovic/ngSemantic#35]
Hi,

Any pointers on how to integrate with webpack starter from AngularClass (https://github.com/AngularClass/angular2-webpack-starter)

Cheers,
Jimmy.

**Comment by vladotesanovic** [comment]
Hey,

I forked project and implemented ng-semantic here:
https://github.com/vladotesanovic/angular2-webpack-starter
I didn't do anything particular. I installed ngSemantic and edited index.html to load Semantic UI and jQuery

I am not master in the Web Pack, so i added this in index.html
https://github.com/vladotesanovic/angular2-webpack-starter/blob/master/src/index.html#L20

jQuery, semantic.min.js and semantic.min.css should be loaded via Web Pack too, but  you can explore more on that.

**Comment by JimmyMagee** [comment]
Excellent, that works a treat! thanks Vlado.
