### ISSUE TITLE
Passing callback into Sidebar

### ISSUE THREAD

**Issue by simonhull** [vladotesanovic/ngSemantic#37]
Trying to get the onHide callback working on the sidebar,  I figured it should only be a matter of passing the callback into the function like so:
`invertedSidebar.show({transition: 'push', onHide: toggle()})`

Nothing happens with this approach, however.  Is there a different way of triggering functions using the callbacks?

**Comment by vladotesanovic** [comment]
Hey Simon,

Don't pass function and don't call it immediately, just pass it as variable:

`For example: <sm-button class="positive icon" icon="sidebar" (click)="invertedSidebar.show({transition: 'overlay', 'onHide': next})">`

and in component:

`export class MyComponent {
    next() {
        console.log('a');
    }
}`
