### ISSUE TITLE
Semantic Installation not triggered

### ISSUE THREAD

**Issue by OClement** [vladotesanovic/ngSemantic#4]
Quoting `Readme.md`:

> Installation
    npm install ng-semantic --save
    **Semantic UI installation will be triggered**. Semantic UI must be installed in public folder ( dist folder must be public )

When installing through npm, the Semantic-Ui installation is not triggered
Is that expected now?

Using Windows 10, NodeJs 5.2.0, NPM 3.3.12

**Comment by vladotesanovic** [comment]
No, it is not. I want to decouple semantic from this package.

I will update package and readme files.

**Comment by vladotesanovic** [comment]
I removed SUI from devDependencies.
You must download it separately and include it in your entry file ( index.html )
