### ISSUE TITLE
How to use sidebar.show() in other component?

### ISSUE THREAD

**Issue by humphrycc** [vladotesanovic/ngSemantic#41]
I want to use `<a (click)="sidebar.show(some options...)">show</a>` and define sidebar in other component as `<sm-sidebar class="..." #sidebar></sm-sidebar>`, but it does not work.

How can I do this, maybe not sm-sidebar, but some ng2 setting? handle by element id?

**Comment by vladotesanovic** [comment]
You can't define ``` <sm-sidebar class="..." #sidebar></sm-sidebar> ``` in other component!

If you want to do like that ( i don't see reason for that ) than you need to implement some sort of Components interaction, which will pass that variable trough components:
https://angular.io/docs/ts/latest/cookbook/component-communication.html
