### ISSUE TITLE
Doesn't work with Angular CLI

### ISSUE THREAD

**Issue by rajjejosefsson** [vladotesanovic/ngSemantic#42]
Using the angular cli gives me the following.

`Error: Uncaught (in promise): Error: Error: XHR error (404 Not Found) loading http://localhost:4200/vendor/ng-semantic/ng-semantic.js`

**Comment by wgbn** [comment]
I am also having the same problem

**Comment by wgbn** [comment]
managed to solve my problem! In fact I was missing add ng-semantic reference to the **angular-cli-build.js** file

```
vendorNPMFiles: [
  // other packages here
  'ng-semantic/**/*',
]
```

**Comment by vladotesanovic** [comment]
Yep,
https://github.com/vladotesanovic/ngSemantic#angular-cli-configuration

But RC.5 is out now, so maybe there will be changes on that one too.
