### ISSUE TITLE
Dart version

### ISSUE THREAD

**Issue by nimaen** [vladotesanovic/ngSemantic#48]
Hey, great job so far in TS.
Was wondering if I could suggest a Dart version ?
I don't mind doing it though.

**Comment by vladotesanovic** [comment]
Tnx, 

I am not good at Dart, and i don't have plan to learn it. If you are good at Dart, you can start with implementation?

**Comment by nimaen** [comment]
Fair enough.
Dart is really close to Typescript though :)
How do you want me to structure it ?

**Comment by nimaen** [comment]
Let's think about it in another project in future 😉
