### ISSUE TITLE
Incorrect attribute linking to core Semantic CSS 

### ISSUE THREAD

**Issue by calbear47** [vladotesanovic/ngSemantic#57]
Great project, good work so far!

On your demo site, https://ng-semantic.herokuapp.com/#/, you incorrectly use the 'src' instead of 'href' to link to the CDN providing the core semantic CSS.

**Currently:** `<link rel="stylesheet" type="text/css"
src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.2/semantic.min.css">` 

**Should be:** 
`<link rel="stylesheet" type="text/css"
href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.2/semantic.min.css">`

**Comment by vladotesanovic** [comment]
Tnx, fixed :+1:
