### ISSUE TITLE
Can ngSemantic be used with angular-cli@webpack?

### ISSUE THREAD

**Issue by jwuliger** [vladotesanovic/ngSemantic#58]
Hello! Great work here with this wrapper. I love this UI. I have a NG2 app that was created using the new and future standard angular-cli that has webpack 2 built in.

I am able to import `NgSemanticModule` and then I am able to use one of the components in my component.

When I run the app via `ng serve` my app loads up but nothing is shown. No matter which ngSemantic I try to use. The crazy thing is there are no errors.

I was hoping that someone could help me out. I am loading semantic-ui and jquery via the CDN as in the readme file. Should I npm install semantic-ui instead?

**Comment by vladotesanovic** [comment]
Hey,

I created simple repository with SUI and jQuery, based on Anglar CLI ( with webpack ) https://github.com/vladotesanovic/angular2-cli-webpack

I have no problem with ```ng serve``` . Can you compare my and yours installation?

**Comment by jwuliger** [comment]
Wow thank-you so much. I was so close. I was trying to include the css in the bundle instead of loading it directly in index.html. I also had my require for jQuery in the wrong file. I greatly appreciate your help! You saved my day. I hope this can help anyone else trying the same thing. Thanks again for your help!!
