### ISSUE TITLE
[Question] angular2-webpack-starter with ng-semantic

### ISSUE THREAD

**Issue by DjolePetrovic** [vladotesanovic/ngSemantic#60]
Has anybody integrated ng-semantic with the [angular2-webpack-starter](https://github.com/AngularClass/angular2-webpack-starter) from AngularClass?

**Comment by vladotesanovic** [comment]
Yep,

I did, but it was for Angular rc.4 https://github.com/vladotesanovic/angular2-webpack-starter 

Probably slight updates are required...

**Comment by DjolePetrovic** [comment]
Hvala!

**Comment by vladotesanovic** [comment]
Sve najbolje :)
