### ISSUE TITLE
With regards to jquery

### ISSUE THREAD

**Issue by 4tron** [vladotesanovic/ngSemantic#7]
Are you going to be leaving jquery as a dependency for the project? I have not used ng2 but ng1's approach was to more or less leave it out.

**Comment by vladotesanovic** [comment]
Yes i am planning to use it because SUI depends on it, it would be really great to rewrite everything on vanilla js with use of ngAnimation.

**Comment by qlonik** [comment]
Hello. Could you specify necessary jquery version as peer dependency of this project? This way when it is installed with npm, developer will be notified to resolve peer dependency. Thanks!

**Comment by 4tron** [comment]
pretty sure it works with jQuery 1.12.4. maybe create a fork to pull request with this
```
"peerDependencies": {
    "jquery": "1.12.x"
  }
```

**Comment by vladotesanovic** [comment]
Semantic UI requires jQuery 2.1.4, please use that version for optimal performance. 

Putting it as peerDependencies is not bad option at all.

**Comment by 4tron** [comment]
If it works on 2.1.4 it should by default work with 1.12.4 with just more browser support

**Comment by vladotesanovic** [comment]
Ok, that have sense.

I will update documentation regarding that.

**Comment by vladotesanovic** [comment]
I tested ngSemantic with jQuery slim version ( https://code.jquery.com/jquery-3.0.0.slim.min.js ) without success.

**Comment by henninga** [comment]
I would love to see a jquery free version of this. We're using bootstrap 4 now, but SUI is something I'm really considering but jquery is a tough pill to swallow.

**Comment by nimaen** [comment]
That would take a big amount of time since all directives are wrappers around SUI's jQuery call.
