### ISSUE TITLE
sm-tab dynamic display

### ISSUE THREAD

**Issue by tspayne87** [vladotesanovic/ngSemantic#73]
I am attempting to use ngIf on a sm-tab, this works perfectly fine the first time the object is rendered however, if the ngIf statement changes it will get unexpected behaviors.  For instance if the ngIf starts out as false and than turns to true the tab will be added however the javascript will not allow for clicking on the tab.  Also, if its done the opposite of the example everything works as expected.

**Comment by vladotesanovic** [comment]
Hello,

That is true, because at the initialization DOM element is not present. 
Than we need to implement AfterContentChecked and re run ```jQuery.tab()``` function, i'll try

**Comment by vladotesanovic** [comment]
It is fixed in: ng-semantic@1.1.5 version
