### ISSUE TITLE
Updating to the RC6 should generate at least a minor release

### ISSUE THREAD

**Issue by nimaen** [vladotesanovic/ngSemantic#76]
At the moment, only a patch version has been done.
However, the rc6 release of Angular introduced some breaking changes as well (NgModule).
We might change the version of ng-semantic to be a minor (let's be a bit backward compatible) 😄

**Comment by vladotesanovic** [comment]
ngSemantic was 0.0.x version before RC.5, after RC.5 and breaking changes, i set version to be 1.1.x

**Comment by nimaen** [comment]
Oh, my bad then :)
