### ISSUE TITLE
angular2 2.0.0-beta.11 removes @View - breaks ng-semantic

### ISSUE THREAD

**Issue by Coaden** [vladotesanovic/ngSemantic#8]
I received error message:
angular2-polyfills.js:332 Error: TypeError: core_1.View is not a function(…)

Afer a little debugging, I realized 'angulars/core' doesn't have a View() class which is now breaking the ng-semantic components.  I've looked at your code and it looks like all you need to do is move your @View values into the @Component.

Please see:
https://github.com/angular/angular/commit/f9fb72fb0e9bcbda7aeebbf8321ce5d70d78ecee

I'll try rolling back to beta.9 for now.

**Comment by vladotesanovic** [comment]
Updated to Beta.13
