### ISSUE TITLE
Problem creating a sm-select component

### ISSUE THREAD

**Issue by fgtdr** [vladotesanovic/ngSemantic#81]
Hi vladotesanovic,

I have a problem, actually 2 problems:

1. Do not use English well, I apologize for writing.
2. I'm using sm-select component, but does not work as expected. Do not load the placeholder. The label attribute does not work.

In this plunker I try to show my problem:
[http://plnkr.co/edit/TS4nQomysX2s3PZ6za3U?p=preview](url)

Another thing that intrigues me, By modifying the sample files, this is not reflected in the demo app. Why?

Thanks for your help...
Excellent work!

**Comment by fgtdr** [comment]
Regarding the demo,

In the file package.json, I changed the:

"scripts": {
    "demo:lint": "tslint -c ./tslint.json 'demo/app/**/*.ts'",
    "library:lint": "tslint -c ./tslint.json 'ng-semantic/**/*.ts'",
    "demo:server": "node server.js",
    "typings": "typings install",
    "tsc:w": "tsc -w -p './demo'",
    "start": "tsc && concurrently \"tsc -w\" \"npm run tsc:w\" \"lite-server -c dev.config.js\" ",
    "library:bundle": "tsc && rm -rf bundles && node library.builder.js",
    "demo:bundle": "tsc -p './demo' && node demo.builder.js"
  },

by

"scripts": {
    "demo:lint": "tslint -c ./tslint.json 'demo/app/**/*.ts'",
    "library:lint": "tslint -c ./tslint.json 'ng-semantic/**/*.ts'",
    "demo:server": "node server.js",
    "typings": "typings install",
    "tsc:w": "tsc -w -p ./demo",
    "start": "tsc && concurrently \"tsc -w\" \"npm run tsc:w\" \"lite-server -c dev.config.js\" ",
    "library:bundle": "tsc && rm -rf bundles && node library.builder.js",
    "demo:bundle": "tsc -p ./demo && node demo.builder.js"
  },

**Comment by nimaen** [comment]
Hi,

You have an error because you're using ReactiveFormsModule directives & components in a module that does not import them.
To sum up, add the ReactiveFormsModule in your main module in this case.
See your plunker updated : [http://plnkr.co/edit/P0tS5xCW1D9fpo8yhpxN?p=preview](http://plnkr.co/edit/P0tS5xCW1D9fpo8yhpxN?p=preview)

**Comment by fgtdr** [comment]
Thank nimaen...

**Comment by nimaen** [comment]
You're welcome 😄
