### ISSUE TITLE
Set selected options on multiple selection

### ISSUE THREAD

**Issue by tomtobac** [vladotesanovic/ngSemantic#84]
Thanks for the components! Great job! 

I am trying to fill a multiselect of countries with async call but when I try to check the selected items I can not... Its possible?
`
<option *ngFor="let country of countries" [selected]="country.selected" [value]="country.value">{{country.option}}</option>
`

Should be like this, right?

**Comment by nimaen** [comment]
Hey :)

Looking at the code atm, you can only use the model property to achieve this.
Havent tested it with multiple values though.

**Comment by tomtobac** [comment]
@nimaen 
Thanks for answering!

I am still learning `Angular 2` but are you refering to this? 

`
    @Input("model")
    set model(data: string|number) {
        if (data) {
            setTimeout(() => {
                jQuery(this.select.nativeElement).dropdown("set selected", data);
            }, 1);
        }
    }
`

So, I should pass my model (class?) like this: 

`
export class Country {
  option: string;
  selected: boolean;
  value: string;
}
...
<sm-select [model]="Country" .. >

`

No idea what I am doing! >__<

**Comment by nimaen** [comment]
You can use the example like this :
```html
<sm-select [options]="{direction: 'upward'}" [(model)]="selectedCities" class="fluid multiple">
  <option *ngFor="let city of cities" [value]="city">{{city}}</option>
</sm-select>
```
```typescript
selectedCities: Array<String> = ["New York", "Belgrade"];
cities: Array<string> = ["New York", "Belgrade", "Stockholm", "Sarajevo"];
```

Or you can use the `control` input to pass value on the model.
Please refer to the official documentation or an article like this : http://blog.angular-university.io/introduction-to-angular-2-forms-template-driven-vs-model-driven/

**Comment by tomtobac** [comment]
Thanks for the help! Works perfect! Thanks a lot! :+1:

**Comment by nimaen** [comment]
You're welcome ;)
