### ISSUE TITLE
activate modal from code if condition is !true

### ISSUE THREAD

**Issue by fhdk** [vladotesanovic/ngSemantic#87]
I am trying to figure out how to do this. The only thing that bugs me is the modal.

I have a condition which evaluates to true/false.

if !condition => modal.show({closable:false, inverted:true})

in modal select one of three actions and create the condition in localStorage

I seem so totally not getting it - I cant figure out how to show the modal from code. That might strive from the fact that I know nothing about jQuery but nevertheless.

I have tried to inject a ccsclass  ```class="{{cssClass}}"``` and setting it to ´´´active´´´ and this get me some of the way but the modal is dropping out of sight.

When searching in issues i dropped on someone loading properties from api. It lead me to this [http://plnkr.co/edit/QVHFPLi5leGqRJ8ZEV4P?p=preview](http://plnkr.co/edit/QVHFPLi5leGqRJ8ZEV4P?p=preview)

I have tried to recreate a working sample [https://github.com/fhdk/a-modal-test](https://github.com/fhdk/a-modal-test) but finds that ```.show``` is not found on ElementRef

Is it possible that You could point me in the right direction?

By the way :+1:  thanks for taking the time

**Comment by fhdk** [comment]
in app.component
```import { SemanticModalComponent } from 'ng-semantic';```

```@ViewChild('myModal') myModal: SemanticModalComponent ;```

**Comment by brjadams** [comment]
@fhdk any chance you have a finished example of what you did?
I'm not able to just do myModal.show() to trigger the child component dialog. Perhaps I'm misunderstanding.
Thanks

**Comment by fhdk** [comment]
@brjadams [https://github.com/fhdk/a-modal-test](https://github.com/fhdk/a-modal-test)
