### ISSUE TITLE
Can't bind to 'formGroup' since it isn't a known property of 'form'

### ISSUE THREAD

**Issue by smartm0use** [vladotesanovic/ngSemantic#88]
Hello, i get that error when i try to use the code available [here](https://ng-semantic.herokuapp.com/#/elements/form):

	<form class="ui form" [formGroup]="form"> 
		<sm-loader [complete]="!formSubmited" class="inverted" text="Loading..."></sm-loader>
		<div class="field">
			<sm-input label="Name" [control]="form.controls.nameControl" placeholder="Enter name..."></sm-input>
		</div>
		<div class="field">
			<sm-input label="E-mail" [control]="form.controls.emailControl" placeholder="Enter e-mail..."></sm-input>
		</div>
		<div class="field">
			<sm-checkbox label="I agree to the Terms and Conditions" [control]="agreeControl"></sm-checkbox>
		</div>
		<sm-button (click)="submit()" [disabled]="!form.valid" class="primary">Login</sm-button>
	</form>

I'm using Angular 2.0.0 (with SystemJS as module loader) and i installed both `semantic-ui` and `ng-semantic` Node modules. Do you know why i'm getting this error?

**Comment by nimaen** [comment]
Hi, can you post the actual error please ?
There is no error in your message...

**Comment by smartm0use** [comment]
The error was in the title. Anyway i solved importing even `ReactiveFormsModule` in `app.module.ts` file.

**Comment by nimaen** [comment]
Oh well indeed, my bad :)
