### ISSUE TITLE
Problems to install in MAC

### ISSUE THREAD

**Issue by farnetani** [vladotesanovic/ngSemantic#93]
I have a problem, result the error:

ng-semantic@1.1.11 start /Volumes/WINDOWS/Dropbox (Pessoal)/Dropbox - 2016/www-2016/Angular2/ngSemantic
> tsc && concurrently "tsc -w" "npm run tsc:w" "lite-server -c dev.config.js" 

error TS6053: File '/Volumes/WINDOWS/Dropbox (Pessoal)/Dropbox - 2016/www-2016/Angular2/ngSemantic/typings/index.d.ts' not found.

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! ng-semantic@1.1.11 start: `tsc && concurrently "tsc -w" "npm run tsc:w" "lite-server -c dev.config.js" `
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the ng-semantic@1.1.11 start script 'tsc && concurrently "tsc -w" "npm run tsc:w" "lite-server -c dev.config.js" '.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ng-semantic package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc && concurrently "tsc -w" "npm run tsc:w" "lite-server -c dev.config.js" 
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ng-semantic
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ng-semantic
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Volumes/WINDOWS/Dropbox (Pessoal)/Dropbox - 2016/www-2016/Angular2/ngSemantic/npm-debug.log

**Comment by farnetani** [comment]
My debug.log

sh-3.2# cat npm-debug.log 
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@3.10.3
3 info using node@v6.6.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle ng-semantic@1.1.11~prestart: ng-semantic@1.1.11
6 silly lifecycle ng-semantic@1.1.11~prestart: no script for prestart, continuing
7 info lifecycle ng-semantic@1.1.11~start: ng-semantic@1.1.11
8 verbose lifecycle ng-semantic@1.1.11~start: unsafe-perm in lifecycle true
9 verbose lifecycle ng-semantic@1.1.11~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Volumes/WINDOWS/Dropbox (Pessoal)/Dropbox - 2016/www-2016/Angular2/ngSemantic/node_modules/.bin:/usr/local/bin:/Library/Frameworks/Python.framework/Versions/3.5/bin:/usr/local/sbin:/Applications/MAMP/Library/bin:/Applications/MAMP/bin/php/php5.6.10/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin/npm:/Users/farnetani/Library/Android/sdk:/Users/farnetani/Library/Android/sdk/tools:/Users/farnetani/Library/Android/sdk/platform-tools
10 verbose lifecycle ng-semantic@1.1.11~start: CWD: /Volumes/WINDOWS/Dropbox (Pessoal)/Dropbox - 2016/www-2016/Angular2/ngSemantic
11 silly lifecycle ng-semantic@1.1.11~start: Args: [ '-c',
11 silly lifecycle   'tsc && concurrently "tsc -w" "npm run tsc:w" "lite-server -c dev.config.js" ' ]
12 silly lifecycle ng-semantic@1.1.11~start: Returned: code: 2  signal: null
13 info lifecycle ng-semantic@1.1.11~start: Failed to exec start script
14 verbose stack Error: ng-semantic@1.1.11 start: `tsc && concurrently "tsc -w" "npm run tsc:w" "lite-server -c dev.config.js" `
14 verbose stack Exit status 2
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid ng-semantic@1.1.11
16 verbose cwd /Volumes/WINDOWS/Dropbox (Pessoal)/Dropbox - 2016/www-2016/Angular2/ngSemantic
17 error Darwin 15.5.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
19 error node v6.6.0
20 error npm  v3.10.3
21 error code ELIFECYCLE
22 error ng-semantic@1.1.11 start: `tsc && concurrently "tsc -w" "npm run tsc:w" "lite-server -c dev.config.js" `
22 error Exit status 2
23 error Failed at the ng-semantic@1.1.11 start script 'tsc && concurrently "tsc -w" "npm run tsc:w" "lite-server -c dev.config.js" '.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the ng-semantic package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     tsc && concurrently "tsc -w" "npm run tsc:w" "lite-server -c dev.config.js"
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs ng-semantic
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls ng-semantic
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by frankadrian** [comment]
It seems like the typings did not install properly! Try running the command manually: `npm run typings`

**Comment by farnetani** [comment]
Yes...now work! Cool! Thanks a lot!

**Comment by nimaen** [comment]
In fact, with typescript v2+, we should not use typings but install definition files from the @type npm scope instead. @vladotesanovic, need to also plan that. I create an issue.
