### ISSUE TITLE
sm-checkbox doesn't work

### ISSUE THREAD

**Issue by smartm0use** [vladotesanovic/ngSemantic#99]
When i try to use `sm-checkbox` i get the following error in the browser console:

`core.umd.js:3462 EXCEPTION: Uncaught (in promise): Error: Error in ./SemanticCheckboxComponent class SemanticCheckboxComponent - inline template:0:19 caused by: Cannot read property 'value' of undefined`

Can you please fix it?

**Comment by nimaen** [comment]
Hi, please give your full example.

**Comment by smartm0use** [comment]
Here is my full example:

`<sm-checkbox label="Receip"></sm-checkbox>`

**Comment by nimaen** [comment]
Ok, I've created another issue for this.
Should be resolved by #100.
